### ISSUE TITLE
Publish eglot-java on ELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [yveszoundi/eglot-java#1]
Hi,

would you consider adding this package to ELPA? If so, may I suggest to get in touch with @phikal to check what you need to do?

Thank you!

**Comment by yveszoundi** [comment]
Hi @manuel-uberti,

Thanks for asking and checking out this repository. Sure for ELPA, especially if this package could be useful to others. 

I have gone through the process before for MELPA, I would definitely want to understand what's required for ELPA. 
I'll connect with @phikal next week in that respect.

**Comment by manuel-uberti** [comment]
Fantastic, thanks a lot for this.

**Comment by yveszoundi** [comment]
@phikal, was the ELPA process smooth enough from your perspective? (copyright assignment, etc.)

I feel like publishing to MELPA is likely less painful and time consuming :-).

**Comment by manuel-uberti** [comment]
FWIW, I published [flymake-proselint](https://elpa.gnu.org/packages/flymake-proselint.html) to ELPA, and it was as simple as few mail exchanges. Although I already had the required copyright agreement.

**Comment by phikal** [comment]
The copyright assignment is a one-time thing for most contributors, but otherwise all you need to do is to send an Email to emacs-devel@gnu.org suggesting to add your package.

**Comment by yveszoundi** [comment]
I decided to go with MELPA, as the process is less involved from my perspective.

I'm currently waiting for any additional feedback on my pull request: https://github.com/melpa/melpa/pull/7814

**Comment by manuel-uberti** [comment]
OK, thanks anyway. I guess we can close this one then.

**Comment by phikal** [comment]
I am sad to hear that, as Eglot is distributed per GNU ELPA, but it is your decision.

And if I may ask, what made the process for ELPA seem "more involved". I'd like to help make it more straight-forward, but I fail to see what the issue is.

On 9 December 2021 07:04:19 CET, Yves Zoundi ***@***.***> wrote:
>I decided to go with MELPA, as the process is less involved from my perspective.
>
>I'm currently waiting for any additional feedback on my pull request: https://github.com/melpa/melpa/pull/7814
>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brotzeit** [comment]
No offense, but the popularity of elpa compared to melpa shows IMO that the emacs community doesn't understand the value of the copyright assignment requirement(neither do I). But maybe NonGNU ELPA is an alternative. I don't know how it differs from elpa, but probably it's some kind of middle ground ?

**Comment by phikal** [comment]
brotzeit ***@***.***> writes:

> No offense, but the popularity of elpa compared to melpa shows IMO
> that the emacs community doesn't understand the value of the copyright
> assignment requirement(neither do I). But maybe NonGNU ELPA is an
> alternative. I don't know how it differs from elpa, but probably it's
> some kind of middle ground ?

NonGNU ELPA and GNU ELPA work exactly the same way (setting aside minor
differences like auto-updating).  In this case I should have clarified
that when I wrote "ELPA" (not "GNU ELPA"), I meant either of the two.

-- 
	Philip Kaludercic

**Comment by phikal** [comment]
Eh, yes -- I see that is a matter of administration, not how it works (technically).
