### ISSUE TITLE
Support running specific @Test method

### ISSUE THREAD

**Issue by uqix** [yveszoundi/eglot-java#12]
### Problem

Currently it's only possible to run tests for an entire class. 

#### Approach

The `eglot-java-run-test` function behavior will be changed:

- If there's an enclosing method near the current cursor location ("the point"), that specific method will be executed
- Otherwise, all the tests in the current file will be executed (current behavior at this time)

#### Technical constraints

There's no built-in LSP server handler that will return automatically all the available test methods in a given file.

If the mouse cursor is near a helper method, this package will blindly assume that "you know what you're doing" and you'll get an error message from the Junit console logs.

**Comment by yveszoundi** [comment]
Closed by pull request https://github.com/yveszoundi/eglot-java/pull/19
