### ISSUE TITLE
add function for installing language server 

### ISSUE THREAD

**Issue by Gavinok** [yveszoundi/eglot-java#2]
One of the great things about getting java development going on lsp-mode is the ability for lsp-mode to install jdtls for you. would be great to have that added here.

**Comment by yveszoundi** [comment]
Thanks for the feedback @Gavinok, the function does exist already. I don't know if I'm missing something per points below.

-  At the beginning of the readme, I do mention the following: "..._The Eclipse JDT Language Server is automatically installed_..". Is it something that **you didn't see** immediately or **it didn't work** in your case? It's hard to guess.
- The existence check of the Eclipse JDT LS server is not really robust, i.e. [there's nothing beyond a directory check](https://github.com/yveszoundi/eglot-java/blob/main/eglot-java.el#L606).

It kinda of "work on my machine", so again not sure if it didn't work for you or if you didn't notice  that the functionality exists.

**Comment by Gavinok** [comment]
My mistake I was not reading that correctly. Thanks for the correction.
