### ISSUE TITLE
Does not work with current eglot master

### ISSUE THREAD

**Issue by hjudt** [yveszoundi/eglot-java#3]
While automatically installing the eclipse lsp works fine, there no longer is a eglot--eclipse-jdt or similar in eglot master, so starting it fails.

**Comment by hjudt** [comment]
https://github.com/joaotavora/eglot/commit/de3004fb52bc87eb7088894dbc4047101004e366

**Comment by hjudt** [comment]
Also see for setup instructions: https://github.com/joaotavora/eglot/pull/864

**Comment by yveszoundi** [comment]
Thanks @hjudt , sorry for the late response. This should be resolved now per notes below.

I caught up with recent `eglot` code changes and updated `eglot-java` accordingly.
- Some code that I was relying on was removed from `eglot`, I added the relevant bits to `eglot-java`
- I also provided the ability to pass additional custom JVM arguments to the Eclipse JDT LSP server (`eglot-java-eclipse-jdt-args`  customizable variable): This can be useful for Lombok support, heap size parameters, etc.

I run some quick tests with the latest versions of eglot and a fresh automatically installed Eclipse JDT LSP server. It "works on my machine", please feel free to re-open if you still encounter issues.

**Comment by hjudt** [comment]
Thanks for the update. I have been able to configure eglot with the Eclipse JDT LSP server after getting very helpful responses at [this eglot discussion](https://github.com/joaotavora/eglot/discussions/888). Note it is not needed to add another customization variable to achieve this, but one can instead use the existing eglot machinery to do it. Here is my (definitely working) configuration, based on the discussion linked before:
```
  (defvar eglot/initialization-options-map (make-hash-table :size 5))

  (cl-defmethod eglot-initialization-options ((server eglot-lsp-server))
    (if-let ((init-options (gethash (eglot--major-mode server) eglot/initialization-options-map)))
        init-options
      eglot--{}))

  (cl-defmethod eglot-execute-command (_server (_cmd (eql java.apply.workspaceEdit)) arguments)
    "Eclipse JDT breaks spec and replies with edits as arguments."
    (mapc #'eglot--apply-workspace-edit arguments))

  (add-to-list 'eglot-server-programs
               `(java-mode "jdtls"
                           "--jvm-arg=-XX:+UseStringDeduplication"
                           "-data" ,(expand-file-name "emacs/workspace" (xdg-cache-home))
                           ,(concat "--jvm-arg=-javaagent:" (expand-file-name "~/projects/java/lombok.jar"))))

  ;; See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
  (puthash 'java-mode
           `(:settings
             (:java
              (:completion
               (:importOrder "java;javax;org;com;lombok")
               :configuration
               (:runtime [(:name "JavaSE-1.8" :path "/usr/lib/jvm/openjdk-bin-8")
                          (:name "JavaSE-11" :path "/usr/lib/jvm/openjdk-bin-11" :default t)
                          (:name "JavaSE-17" :path "/usr/lib/jvm/openjdk-bin-17")])
               :format (:settings (:url ,(expand-file-name "~/projects/java-config/code_format.xml")
                                        :profile "my-profile"))

               ;; NOTE: https://github.com/redhat-developer/vscode-java/issues/406#issuecomment-356303715
               ;; > We enabled it by default so that workspace-wide errors can
               ;; > be reported (eg. removing a public method in one class would
               ;; > cause compilation errors in other files consuming that
               ;; > method). For large workspaces, it may make sense to be able
               ;; > to disable autobuild if it negatively impacts performance.
               :autobuild (:enabled t)

               ;; https://github.com/dgileadi/vscode-java-decompiler
               ;; WIP: support non standard LSP `java/classFileContents', `Location' items that have a `jdt://...' uri
               ;; https://github.com/eclipse/eclipse.jdt.ls/issues/1384
               ;; nvim impl demo: https://github.com/mfussenegger/dotfiles/commit/3cddf73cd43120da2655e2df6d79bdfd06697f0e
               ;; lsp-java impl demo: https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el
               :contentProvider (:preferred "fernflower")
               :saveActions (:organizeImports nil)))
             :extendedClientCapabilities (:classFileContentsSupport t)
             ;; bundles: decompilers, etc.
             ;; https://github.com/dgileadi/dg.jdt.ls.decompiler
             :bundles ,(let ((bundles-dir (expand-file-name "emacs/eglot/java/bundles" (xdg-cache-home)))
                             jdtls-bundles)
                         (->> (when (file-directory-p bundles-dir)
                                (directory-files bundles-dir t "\\.jar$"))
                              (append jdtls-bundles)
                              (apply #'vector))))
           eglot/initialization-options-map)
```
Because this is based on eglot, it is less likely to break. Note it is still necessary to apply that **workspaceEdit** workaround for eglot, otherwise some code actions won't work.

You might incorporate parts of this somehow into eglot-java as you suggested, though I now prefer to just leave the above code in my config. IMHO, they should put an example like this in the eglot README because it gives good instructions on how to configure settings for a language server in general, not only java.

Apart from that, I have not yet been able yet to try eglot-java and find out what it improves besides the initial configuration because of the late breakage, which should be fixed now.
