### ISSUE TITLE
Lombok does not always seem to work correctly

### ISSUE THREAD

**Issue by trev-dev** [yveszoundi/eglot-java#30]
I cannot imagine why it would work in some cases, but not in others, but throughout the majority of the project things work fine, until I see the `@Getter` annotation.

Everything works fine when I compile the thing.

Also, my lombok verrsion (1.18.30) seems to work fine with `lsp-mode` and nvim-jdtls.

When things go wrong, I get a lint error at the top of the buffer which reads:
`Java [0]: Lombok annotation handler class lombok.eclipse.handlers.HandleGetter failed - See error log.` and sometimes, but not always, missing references down the buffer from there.

My vmargs are set as such:

```elisp
(defun td-eglot-java-setup ()
  (setq eglot-java-eclipse-jdt-args (list (concat "-javaagent:"
                                               td-eglot-java-lombok-path)))
  (td-bind-keys '(("C-c e n" . eglot-java-file-new)
                  ("C-c e x" . eglot-java-run-main)
                  ("C-c e t" . eglot-java-run-test)
                  ("C-c e N" . eglot-java-project-new)
                  ("C-c e T" . eglot-java-project-build-task)
                  ("C-c e R" . eglot-java-project-build-refresh))
                eglot-java-mode-map))

(add-hook 'eglot-java-mode-hook 'td-eglot-java-setup)
```

When I check the jdt args at run time, they look pretty good to me:
```
Its value is
("-javaagent:/home/trev/.emacs.d/eglot-java/lombok/lombok.jar" "-jar" "/home/trev/.emacs.d/share/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.6.700.v20231214-2017.jar" "-configuration" "/home/trev/.emacs.d/share/eclipse.jdt.ls/config_linux" "-data" "/home/trev/.emacs.d/eglot-java-eclipse-jdt-cache/ba359c4c589a8cb98349d0107123787e")
Original value was nil
```

Any ideas as to what's going on here?

**Comment by trev-dev** [comment]
Hey, sorry.  I just don't have the bandwidth to keep going with this.

**Comment by yveszoundi** [comment]
Adding this link for future references
https://sideshowcoder.com/2025/02/23/eglot-lombok-and-jtdls/

**Comment by ltylty** [comment]
i write this package  https://github.com/ltylty/eglot-java-lombok

just use it as follow

```
(use-package eglot-java-lombok :ensure t 
  :vc (:url "https://github.com/ltylty/eglot-java-lombok" :branch "main" :rev :newest)
  :config
  (eglot-java-lombok/init))
```

**Comment by saulotoledo** [comment]
Another alternative for handling Lombok and other Java agents with eglot-java: JAL (Java Agent Loader): https://github.com/saulotoledo/java-agent-loader (On MELPA: https://melpa.org/#/jal)
It is a bit heavier than https://github.com/ltylty/eglot-java-lombok, though, so it is up to you to decide. It would be great to hear from you on the trade-offs as well.
