### ISSUE TITLE
Do not bind C-c l by default

### ISSUE THREAD

**Issue by phikal** [yveszoundi/eglot-java#4]
This key should be reserved for users and never be automatically bound.

**Comment by yveszoundi** [comment]
Thanks for the issue report.

- What do you recommend instead as a default prefix key instead?
- Do you believe that it should be left for users to decide (nil by default and  only automatically bound when not nil)?

I feel like maybe the second option might introduce less friction.

**Comment by yveszoundi** [comment]
I  disabled the default value of the default prefix key `eglot-java-prefix-key`.

- If users like default suggested keybindings, they'll need to explicitly customize `eglot-java-prefix-key` and also toggle  the value of `eglot-java-default-bindings-enabled`
- The keybindings themselves get associated to `eglot-mode-map` and I documented that

**Comment by yveszoundi** [comment]
I can definitely make such a change. I haven't used custom mode maps outside minor modes for  a very long time. 

I'll run some tests later today and apply suggested changes.

**Comment by yveszoundi** [comment]
@phikal , I feel better defining a new minor mode (`eglot-java-mode`) for the keymap.

The user would be in full control of what he/she wants to happen. Do you think that the changes below are good enough?

```elisp
(eglot-java-init)

(add-hook 'eglot-java-mode-hook (lambda ()
                                  (message "do something in eglot-java-mode-hook if you want")))

(define-key eglot-java-mode-map (kbd "C-c l n") #'eglot-java-file-new)
(define-key eglot-java-mode-map (kbd "C-c l x") #'eglot-java-run-main)
(define-key eglot-java-mode-map (kbd "C-c l t") #'eglot-java-run-test)
(define-key eglot-java-mode-map (kbd "C-c l N") #'eglot-java-project-new)
(define-key eglot-java-mode-map (kbd "C-c l T") #'eglot-java-project-build-task)
(define-key eglot-java-mode-map (kbd "C-c l R") #'eglot-java-project-build-refresh)
```

**Comment by yveszoundi** [comment]
I pushed the changes in a new branch bugfix-4-new-minor-mode: https://github.com/yveszoundi/eglot-java/compare/main...bugfix-4-new-minor-mode

For the second question yes, that would be the propose configuration.

If you do have something better to propose, please just send a pull request. It seems that you're a more knowledgeable and passionate emacs user than I am.

**Comment by yveszoundi** [comment]
The new recommended emacs init file configuration is as follow:

```elisp
(add-hook 'java-mode-hook 'eglot-java-mode)
(add-hook 'eglot-java-mode-hook (lambda ()                                        
  (define-key eglot-java-mode-map (kbd "C-c l n") #'eglot-java-file-new)
  (define-key eglot-java-mode-map (kbd "C-c l x") #'eglot-java-run-main)
  (define-key eglot-java-mode-map (kbd "C-c l t") #'eglot-java-run-test)
  (define-key eglot-java-mode-map (kbd "C-c l N") #'eglot-java-project-new)
  (define-key eglot-java-mode-map (kbd "C-c l T") #'eglot-java-project-build-task)
  (define-key eglot-java-mode-map (kbd "C-c l R") #'eglot-java-project-build-refresh)))
```
