### ISSUE TITLE
RFC fixing class rename

### ISSUE THREAD

**Issue by lina-bh** [yveszoundi/eglot-java#41]
At present when doing eglot-rename on a type, the class file is not renamed at the same time and the server sends an error about the two not matching. Doing rename-visited-file confuses the server further because the file open and close events aren't sent. This is pretty annoying for me as i like to chop and change my names pretty often if I'm working on my own project. From what I can see, JDT.LS does send a rename event if the client sends `capabilities.workspaceEdit.resourceOperations: ["rename"]` but Eglot by default does not.

I did have some code that tried to brute force figuring out whether we just renamed a class and to do the rename in Emacs, but it didn't feel safe for a potentially destructive action. The other option I'm thinking of is trying to send the `resourceOperations` capability to the server and listening for rename events inside eglot-java. (Of course the nicer option would be to have this work inside Eglot itself, but I do not have the patience for trying to get code into Emacs git.) Any comments would be welcomed

**Comment by lina-bh** [comment]
Adding resourceOperations to the caps object seems simple enough:
```emacs-lisp
(cl-defmethod eglot-client-capabilities ((server eglot-java-eclipse-jdt))
  (let ((caps (cl-call-next-method server)))
    (when-let* ((workspace (plist-get caps :workspace))
                (workspaceEdit (plist-get workspace :workspaceEdit)))
      (plist-put workspaceEdit :resourceOperations
                 (vector "create" "rename" "delete"))
      (plist-put workspace :workspaceEdit workspaceEdit)
      (plist-put caps :workspace workspace))
    caps))
```
The problem comes on the other end, `eglot--apply-workspace-edit` is not generic so it would appear that it would need to be advised :(

**Comment by lina-bh** [comment]
This code strips out any workspace edits that are not instances of TextDocumentEdit, now need to figure out what to do with them.
```emacs-lisp
(defun eglot-java--apply-workspace-edit-filter-args (args)
  (let* (text-document-edits resource-operations
         (wedit (car args))
         (documentChanges (plist-get wedit :documentChanges)))
    ;; is there some faster way of looping over a vector. or maybe use
    ;; seq-group-by
    (seq-doseq (change documentChanges)
      (if (and (plist-member change :textDocument)
               (plist-member change :edits))
          (push change text-document-edits)
        (push change resource-operations)))
    (plist-put wedit :documentChanges text-document-edits))
  args)
(advice-add 'eglot--apply-workspace-edit :filter-args
            'eglot-java--apply-workspace-edit-filter-args)
```

**Comment by yveszoundi** [comment]
> Of course the nicer option would be to have this work inside Eglot itself, but I do not have the patience for trying to get code into Emacs git.

I understand, I'm stopped reading Emacs mailing lists a long time ago and I'm probably too grumpy to engage in long conversations myself.

I haven't looked at that aspect of the LSP specification yet or detailed handling in eglot. There's some code in `eglot-java`  (it used to be in eglot itself), that can potentially be an entry point for custom logic. 

```
(cl-defmethod eglot-execute-command
    ((_server eglot-java-eclipse-jdt) (_cmd (eql java.apply.workspaceEdit)) arguments)
  "Eclipse JDT breaks spec and replies with edits as arguments."
  (mapc #'eglot--apply-workspace-edit arguments))
```

**Comment by lina-bh** [comment]
Unfortunately `eglot-rename` calls `eglot--request` synchronously, which doesn't go through `eglot-execute-command`.

I've come up with this:

```emacs-lisp
(defcustom eglot-java-advertise-rename nil
  "Whether eglot-java modifies the initialisation object sent to the server to
advertise that we can handle rename requests.

eglot-java overrides `eglot-client-capabilities' and if this variable is non-nil,
attaches 'workspaceEdit.resourceOperations: [\"create\", \"rename\", \"delete\"]'
to the capabilties object. `eglot--apply-workspace-edit' is patched (advised) by
`eglot-java--apply-workspace-edit-around' to handle rename requests from the
server. Creation or deletion requests are not supported."
  :type 'boolean
  :group 'eglot-java)

(cl-defmethod eglot-client-capabilities ((server eglot-java-eclipse-jdt))
  "When `eglot-java-advertise-rename' is non-nil, attach
'workspaceEdit.resourceOperations: [\"create\", \"rename\", \"delete\"]' to the
capabilities supported by Eglot so that the server will request to rename files."
  (let ((caps (cl-call-next-method server)))
    (when eglot-java-advertise-rename
      (when-let* ((workspace (plist-get caps :workspace))
                  (workspaceEdit (plist-get workspace :workspaceEdit)))
        (plist-put workspaceEdit :resourceOperations
                   (vector "create" "rename" "delete"))
        (plist-put workspace :workspaceEdit workspaceEdit)
        (plist-put caps :workspace workspace)))
    caps))

(defun eglot-java--do-rename (old-path new-path)
  (when (or (file-exists-p new-path) (get-file-buffer new-path))
    (error "Would clobber %s" new-path))
  (let ((old-buffer (get-file-buffer old-path)))
    (if (not old-buffer)
        (rename-file old-path new-path)
      (with-current-buffer old-buffer
        (save-buffer)
        (eglot--signal-textDocument/didClose)
        (rename-visited-file new-path)
        (eglot--signal-textDocument/didOpen)))))

(defun eglot-java--apply-resource-operations (ops)
  "Offer to apply rename for each request in OPS. If a file already exists at the
requested path or a buffer is visiting it, refuse to clobber the file."
  (dolist (op ops)
    (if (not (string= "rename" (plist-get op :kind)))
        (message "[eglot-java] Ignoring %s operation" kind)
      (let ((old-path (eglot-uri-to-path (plist-get op :oldUri)))
            (new-path (eglot-uri-to-path (plist-get op :newUri))))
        (if (or (file-exists-p new-path) (get-file-buffer new-path))
             (message "[eglot-java] Refusing to clobber %s" new-path)
          (when
              (y-or-n-p
               (format "[eglot-java] Server wants to rename\n%s to %s\nProceed? "
                       (file-relative-name old-path
                                           (project-root
                                            (eglot--current-project)))
                       (file-relative-name new-path
                                           (file-name-directory old-path))))
            (eglot-java--do-rename old-path new-path)))))))

(defun eglot-java--apply-workspace-edit-around
    (eglot--apply-workspace-edit wedit origin)
  "Patch `eglot--apply-workspace-edit' so that if the server sends resource
operations (create, rename, delete) they are peeled off the list before passing
to Eglot, which cannot handle them. Apply renames if the current project is
managed by eglot-java."
  (let ((edits+ops (seq-group-by (lambda (change)
                                   (if (and (plist-member change :textDocument)
                                            (plist-member change :edits))
                                       :text-document-edit :resource-operation))
                                 (plist-get wedit :documentChanges))))
    (plist-put wedit :documentChanges (cdr (assq :text-document-edit edits+ops)))
    (funcall eglot--apply-workspace-edit wedit origin)
    (when (eglot-java-eclipse-jdt-p (eglot-current-server))
      (eglot-java--apply-resource-operations (cdr (assq :resource-operation
                                                      edits+ops))))))
(advice-add 'eglot--apply-workspace-edit :around
            'eglot-java--apply-workspace-edit-around)
```

This works, I may want to write some tests for it because I'm not too confident in handling edge cases to avoid data loss. As well since this uses `seq.el` and `rename-visited-file` it might need changing for older currently supported Emacsen. 

Advising `eglot--apply-workspace-edit` still feels icky, but unfortunately if Eglot encounters a [`{Create,Delete,Rename}File`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#resourceChanges) event, it throws an error since it doesn't know how to differentiate between it and [TextDocumentEdit](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentEdit). I'm thinking now to just leave the advice as is, but instead wrap `eglot-rename` for the actual rename operation so that it is as non-invasive as possible, and the user can shadow their binding for `eglot-rename` in `eglot-java-mode-map`.

**Comment by lina-bh** [comment]
I get the feeling that handling creating files will be required to get the "move type" code actions working too

**Comment by yveszoundi** [comment]
I spent a little bit of time and I think that I'm close to something that we'll handle "basic file rename" operations. 

I'll let you know shortly, I'm currently testing basic logic of what needs to happen when renaming a class.

**Comment by lina-bh** [comment]
> I spent a little bit of time and I think that I'm close to something that will handle "basic file rename" operations.
> 
> I'll let you know shortly, I'm currently testing basic logic of what needs to happen when renaming a class.

Way ahead of you 😅

**Comment by yveszoundi** [comment]
Closing this issue for now.

- There's an attempt to have the required functionality implemented in [eglot](https://github.com/joaotavora/eglot) (now part of core emacs). 
  - This is where the relevant business logic really belongs, per initial assessments.
  - See https://lists.gnu.org/archive/html/emacs-devel/2024-03/msg00157.html
- Please see comment https://github.com/yveszoundi/eglot-java/issues/41#issuecomment-1975276201 for a "temporary" workaround, until this is addressed in core emacs
