### ISSUE TITLE
can't install and compile eglot-java when version of eglot is 1.17

### ISSUE THREAD

**Issue by Peter-Chou** [yveszoundi/eglot-java#45]
Hi, when I upgrade eglot to 1.17, I can't install the package, it will be stucked at byte compiling. 

![image](https://github.com/yveszoundi/eglot-java/assets/28672146/d408ac39-2490-46c4-a5ef-4f7a0af0d0e4)

it seems there is a conflict with the latest version of eglot

**Comment by yveszoundi** [comment]
I cannot reproduce that error myself on both Linux and Mac OS (brand new vanilla emacs configurations).

#### What I tried

On both Mac OS and Linux with a bare minimum Emacs configuration (configure `package-archives` and then `M-x package-install eglot-java`), I couldn't reproduce your issue:

- Test on a Linux (Emacs 27.1): This is on a Live CD with a brand new emacs configuration (few lines).
- Test on on Mac OS (Emacs 28.2), I don't program on that machine, I just installed the latest eglot `1.17`, and then the latest `eglot-java`

#### My Questions/Recommendations

- Could you attempt reinstalling `eglot-java`, as this could be an intermitent emacs error?
- Are you using a custom emacs distribution (e.g., doom emacs, spacemacs or one of those things)?
  - If yes, could you try on a basic "plain emacs" with just the bare minimum required?
  - If not, do you think tha something in your configuration could prevent the code from compiling? Do you have any logs? (e.g. *Compile Log* buffer contents, or *Messages* buffer contents)?
- What is your emacs version? (`M-x emacs-version`)

**Comment by yveszoundi** [comment]
Essentially per previous message, I have no issue with pretty much a minimal emacs configuration.

That suggests that either you had intermittent emacs errors or there's another issue at play (e.g., emacs distribution such as "doom emacs" or custom emacs settings). It's hard to tell without further information per previous questions.

![eglot-java-compile-issue](https://github.com/yveszoundi/eglot-java/assets/5206067/3061d824-a4dc-4390-99e6-6c67b9be280b)

**Comment by Peter-Chou** [comment]
thanks so much for your attempt. I will further check this problem.
