### ISSUE TITLE
Standalone folder JUnit no test found

### ISSUE THREAD

**Issue by amusingimpala75** [yveszoundi/eglot-java#49]
I have a single file containing a JUnit test. But JDT.LS says it cannot import `org.junit`, and `eglot-java-run-test` fails because `No test found in current file! Is the file saved?` (it is). `eglot-java-run-main` still works fine however.

Is this an intended use case, or does the file need to be part of a Maven/Gradle project?

For reference, IntelliJ is quite capable of doing single file standalone 'projects' like this, including tests.

```java
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class TestClassTest {
    public static void main(String[] args) {
	System.out.println("Hello, World!");
    }

    @Test
    public void testFoo() {
	assertTrue(true);
    }
}
```

**Comment by yveszoundi** [comment]
`eglot-java` it's just a thin wrapper on top of `eglot` (underlying `project.el` library). There's no special support for standalone files. So yes, only Maven/Gradle projects will work (by default).

- Unless you stick to built-in JDK classes in a single file, surprises can be expected. A project would be whatever `project.el` supports such as folders under version control, with a fallback to file markers (Maven pom, Gradle files or Eclipse .project files -> if I recall correctly).
- I think that under the hood, jdt.ls will create a concept of project with just that file (i.e., no knowledge of JUnit libraries). The built-in JUnit support in `eglot-java` only resolves around how tests are run.

You might be able to get around that by adding  LSP startup JVM arguments and custom Elisp code (not sure that that would be practical, without lots of code and customization).

**Comment by amusingimpala75** [comment]
Okay, so after playing around with it a bit, it's really not that bad. There's only two things that I had to change to get this working.

First, adding JUnit to the class path. The JUnit runner which is downloaded already contains the necessary classes for compilation (at least for Jupiter), so merely adding that to `settings:java:home:project:referencedLibraries` in the JDT.LS options suffices for compilation and code completion.

Second, I modified `eglot-java-run-test` to always assume the file is a test. This is clearly a hack, but putting this (and the previous injection) behind a `.dir-locals` variable and including " --fail-if-no-tests " should suffice to replace the current scheme.

With those two things in place, I am able to run `eglot-java-run-test`, and it works fine. Is this the sort of thing you would be willing to have in the package? If so, I'd be happy to make a PR to do this.

Side note: personally the test runner output looks better with the `--disable-ansi-colors` option otherwise I got a bunch of escape characters showing up in the compilation buffer.

**Comment by yveszoundi** [comment]
For now, I'd prefer to avoid having those changes in the package.
- There are already few "magic" bits, such as auto-modifying `eglot-server-programs` (by default) and that occasionally causes problems, especially for people that are not familiar with `emacs-lisp`.
- I'm not sure that altering globally and unconditionally `referencedLibraries` to inject JUnit is a good thing. 
  - When I was actively writing code for a living, I'd sometimes struggle with libraries conflicts/incompatibilities when specific versions are to be used for reasons beyond my control...
  - Again, if I am the average John Doe and I have a conflict with let's say some spring JUnit libraries and whatever is injected, it's problematic: I'm confused, I might not read any README (or maybe I won't understand what it implies) or maybe I think that the emacs package is completely broken.

### Colored output and escape characters
Generally speaking, I do not personally care about ansi colors, emojis, etc.
I've had the following settings for many years, please check if that fixes it for the escape characters. If that doesn't work, I'd welcome a PR to disable ansi colors.

```emacs-lisp
(add-hook 'shell-mode-hook                   #'ansi-color-for-comint-mode-on)
(add-hook 'eshell-preoutput-filter-functions #'ansi-color-filter-apply)
(add-to-list 'comint-output-filter-functions #'ansi-color-process-output)
```

**Comment by amusingimpala75** [comment]
I was thinking these things would be disabled by default, and have to be explicitly enabled by the user, but I understand the concern about invasive injections. I'll close this as not planned, but leave my previous comment as a guide should anyone else seek to do something similar.
