### ISSUE TITLE
recent change created invalid property list

### ISSUE THREAD

**Issue by JoshLitt** [yveszoundi/eglot-java#7]
I have a failure with `ensure-eglot` due to these lines.  This can't be serialized to JSON because it's an invalid property list (a tag with 2 values).
https://github.com/yveszoundi/eglot-java/blob/ea51c475e105c891f8206d0fa0b80c9533d0bfaf/eglot-java.el#L146-L149

Moving a left parenthesis seems to fix it, though I'm just guessing that `:import` is another setting of `:java`.
```
          `(:settings (:java (:home ,home)
                       :import (:gradle (:enabled t)))
                      
                      )
```

**Comment by yveszoundi** [comment]
Thanks a lot, it's weird that I didn't notice it.

- I checked your proposed change and that works great.
- I also enabled explicitly the gradle wrapper in java settings, that also seems to work fine 

I'll add documentation notes for Gradle, as there are occasional issues (bundled Gradle version in Eclipse JDT Language server and installed JDK version):
- The safe approach as a developer is to always rely on the Gradle wrapper, accordingly to the [Gradle compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html)).
- As of now the latest Eclipse JDT LS would include the [buildship plugin version 3.17.x](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L14) for Gradle support
- For version `3.17.x` that [translates into Gradle 7.4.2](https://github.com/eclipse/buildship/blob/master/org.gradle.toolingapi/META-INF/MANIFEST.MF)
- Gradle `7.4.2` would not be compatible with let's say `JDK 19`, [the user would need Gradle 7.6](https://docs.gradle.org/current/userguide/compatibility.html), thus why it's best to always use/generate the Gradle wrapper for "clarity" of mind
